[package]
name = "xtask"
edition = "2021"
version.workspace = true
authors.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
color-eyre = { workspace = true }
duct = { workspace = true }
