[package]
name = "polymath-cli"
authors.workspace = true
version.workspace = true
edition = "2021"

[dependencies]
polymath-rs = { path = "../../polymath-rs" }
open = "5.0"
rand = "0.8"
clap = { version = "4", features = ["derive"] }
