[package]
name = "polymath-cli"
version = "0.1.1-alpha.4"
edition = "2021"

[dependencies]
polymath-rs = { path = "../../polymath-rs" }
open = "5.0"
rand = "0.8"
clap = { version = "4", features = ["derive"] }
