[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin20.4-clang"
ar = "x86_64-apple-darwin20.4-ar"

[target.aarch64-apple-darwin]
linker = "o64-clang"
ar = "o64-ar"

[alias]
xtask = "run --package xtask --"
