[package]
name = "polymath-c"
edition = "2021"
authors.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
polymath-rs = { path = "../polymath-rs", version = "0.1.1-alpha.0"}
