[package]
name = "polymath-c"
description = "Polymath C bindings"
edition = "2021"
license = "MIT"
authors.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
polymath-rs = { path = "../polymath-rs", version = "0.1"}
