name: Java Release

on:
  workflow_dispatch:
    inputs:
      version_level:
        type: choice
        description: Version Level
        options:
          - prerelease
          - patch
          - minor
          - major
    secrets:
      GPG_PRIVATE_KEY:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1
      - name: Build Docker Image
        run: docker build . -t build-image
      - name: Make shared libs
        run: docker run --rm -v$(pwd):polymath build-image make
