name: Java Release

on:
  workflow_dispatch:
    inputs:
      version_level:
        type: choice
        description: Version Level
        options:
          - prerelease
          - patch
          - minor
          - major
    secrets:
      GPG_PRIVATE_KEY:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Build Docker Image
        run: docker build . -t build-image
