name: Java Release

on:
  workflow_dispatch:
    inputs:
      version_level:
        type: choice
        description: Version Level
        options:
          - prerelease
          - patch
          - minor
          - major
    secrets:
      GPG_PRIVATE_KEY:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build Docker Image
        run: docker build . -t build-image
      - name: Make shared libs
        run: docker run --rm -v$(pwd):/polymath build-image make
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 21
          server-id: ossrh
          server-username: SONATYPE_USER
          server-password: SONATYPE_PW
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Build with Maven
        run: cd polymath-java && mvn clean install
